version: "2"
linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - goheader
    - govet
    - ineffassign
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    goheader:
      template: |-
        SPDX-License-Identifier: Apache-2.0
        SPDX-FileCopyrightText: 2024-Present Defense Unicorns
    govet:
      disable:
        - shadow
        - fieldalignment
        - unusedwrite
        - printf
      enable-all: true
    nolintlint:
      require-specific: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/defenseunicorns
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
