name: release
description: Tag with the bumped version, and trigger a GitHub release.
inputs:
  new-version:
    description: "The new version to be released"
    required: true

runs:
  using: composite
  steps:
    - name: Download Release Notes
      uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
      with:
        name: release-notes
        path: notes.md

    - name: Get pkg app token
      id: pkg-app-token
      uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c # v1.9.0
      with:
        app-id: ${{ vars.PKG_WORKFLOW_GITHUB_APP_ID }}
        private-key: ${{ secrets.PKG_WORKFLOW_GITHUB_APP_SECRET }}
        owner: defenseunicorns
        repositories: pkg

    - name: Release
      env:
        GH_TOKEN: ${{ steps.pkg-app-token.outputs.token }}
        NEW_VERSION: ${{ inputs.new-version }}
      run: |
        gh release create "$NEW_VERSION" --title "$NEW_VERSION" --notes-file notes.md
      shell: bash
