name: release
description: Given a module name, bump the version based upon the commit(s) since last release.
inputs:
  module:
    description: "The module to be released"
    required: true

runs:
  using: composite
  steps:
    - name: bump module version
      env:
        MODULE: ${{ inputs.module }}
      run: |
        set -euo pipefail
        cd internal/release
        echo "new-version=$(go run main.go "$MODULE")" >> "$GITHUB_OUTPUT"
      shell: bash
