name: release-notes
description: Generate release notes for a given tag
inputs:
  module:
    description: "The module to be released"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: 1.21.x
        cache-dependency-path: |
          internal/release/go.sum
          internal/release/go.mod

    - name: bump module version
      env:
        MODULE: ${{ inputs.module }}
      id: bump-version
      run: |
        cd internal/release
        echo "new-version=$(go run main.go "$MODULE")" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: install git cliff
      env:
        # renovate: datasource=github-tags depName=orhun/git-cliff versioning=semver
        VERSION: 2.1.2
      run: |
        curl --location --output /tmp/git-cliff.tar.gz https://github.com/orhun/git-cliff/releases/download/v${VERSION}/git-cliff-${VERSION}-x86_64-unknown-linux-gnu.tar.gz
        tar -xvzf /tmp/git-cliff.tar.gz -C /tmp
        mv /tmp/git-cliff-${VERSION}/git-cliff /usr/local/bin/
      shell: bash

    - name: generate release notes
      env:
        NEW_VERSION: ${{ steps.bump-version.outputs.new-version }}
        MODULE: ${{ inputs.module }}
      run: |
        git cliff --config cliff.toml --unreleased --tag "$NEW_VERSION" --include-path "$MODULE/**" | tee notes.md
        echo "## $NEW_VERSION" >> notes.md
        cat notes.md >> "$GITHUB_STEP_SUMMARY"
      shell: bash

    - name: upload release notes
      uses: actions/upload-artifact@ef09cdac3e2d3e60d8ccadda691f4f1cec5035cb # v4.3.1
      with:
        name: release-notes
        path: notes.md
