name: Check OCI

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]
    paths:
      - "oci/**"

permissions:
  contents: read

jobs:
  bump-version-and-release-notes:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump-version.outputs.new-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          fetch-depth: 0

      - name: Bump Version and Generate Release Notes
        uses: ./.github/actions/bump-and-notes
        id: bump-version
        with:
          module: "oci"
          pr-title: ${{ github.event.pull_request.title }}
