name: Check Kubernetes

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]
    paths:
      - "kubernetes/**"

permissions:
  contents: read

jobs:
  bump-version-and-release-notes:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump-version.outputs.new-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Bump Version and Generate Release Notes
        uses: ./.github/actions/bump-and-notes
        id: bump-version
        with:
          module: "kubernetes"
          pr-title: ${{ github.event.pull_request.title }}
