name: Release Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - "kubernetes/**"

permissions:
  contents: read

jobs:
  bump-version-and-release-notes:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump-version.outputs.new-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Bump Version and Generate Release Notes
        uses: ./.github/actions/bump-and-notes
        id: bump-version
        with:
          module: "kubernetes"

  release:
    runs-on: ubuntu-latest
    needs: bump-version-and-release-notes
    # contents: write via the GH app
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Download Release Notes
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: release-notes

      - name: Get pkg app token
        id: pkg-app-token
        uses: actions/create-github-app-token@db3cdf40984fe6fd25ae19ac2bf2f4886ae8d959 # v2.0.5
        with:
          app-id: ${{ vars.PKG_WORKFLOW_GITHUB_APP_ID }}
          private-key: ${{ secrets.PKG_WORKFLOW_GITHUB_APP_SECRET }}
          owner: defenseunicorns
          repositories: pkg

      - name: Release
        env:
          GH_TOKEN: ${{ steps.pkg-app-token.outputs.token }}
          NEW_VERSION: ${{ needs.bump-version-and-release-notes.outputs.new-version }}
        run: |
          gh release create "$NEW_VERSION" --title "$NEW_VERSION" --notes-file notes.md
