name: Release OCI

on:
  push:
    branches:
      - main
    paths:
      - "oci/**"

permissions:
  contents: read

jobs:
  bump-version-and-release-notes:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump-version.outputs.new-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Bump Version and Generate Release Notes
        uses: ./.github/actions/bump-and-notes
        id: bump-version
        with:
          module: "oci"

  release:
    runs-on: ubuntu-latest
    needs: bump-version-and-release-notes
    # contents: write via the GH app
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Download Release Notes
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: release-notes

      - name: Get pkg app token
        id: pkg-app-token
        uses: actions/create-github-app-token@ad38cffc07bac6e3857755914c4c88bfd2db4da4 # v1.10.2
        with:
          app-id: ${{ vars.PKG_WORKFLOW_GITHUB_APP_ID }}
          private-key: ${{ secrets.PKG_WORKFLOW_GITHUB_APP_SECRET }}
          owner: defenseunicorns
          repositories: pkg

      - name: Release
        env:
          GH_TOKEN: ${{ steps.pkg-app-token.outputs.token }}
          NEW_VERSION: ${{ needs.bump-version-and-release-notes.outputs.new-version }}
        run: |
          gh release create "$NEW_VERSION" --title "$NEW_VERSION" --notes-file notes.md
