name: Release OCI

on:
  push:
    branches:
      - main
    paths:
      - "oci/**"

permissions:
  contents: read

jobs:
  bump-version-and-release-notes:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump-version.outputs.new-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0

      - name: Bump Version and Generate Release Notes
        uses: ./.github/actions/bump-and-notes
        id: bump-version
        with:
          module: "oci"

  release:
    runs-on: ubuntu-latest
    needs: bump-version-and-release-notes
    # contents: write via the GH app
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0

      - name: Download Release Notes
        uses: actions/download-artifact@9c19ed7fe5d278cd354c7dfd5d3b88589c7e2395 # v4.1.6
        with:
          name: release-notes

      - name: Get pkg app token
        id: pkg-app-token
        uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1.9.3
        with:
          app-id: ${{ vars.PKG_WORKFLOW_GITHUB_APP_ID }}
          private-key: ${{ secrets.PKG_WORKFLOW_GITHUB_APP_SECRET }}
          owner: defenseunicorns
          repositories: pkg

      - name: Release
        env:
          GH_TOKEN: ${{ steps.pkg-app-token.outputs.token }}
          NEW_VERSION: ${{ needs.bump-version-and-release-notes.outputs.new-version }}
        run: |
          gh release create "$NEW_VERSION" --title "$NEW_VERSION" --notes-file notes.md
