name: Release OCI

on:
  push:
    branches:
      - main
    paths:
      - 'oci/**'

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0

      - name: Release
        uses: ./.github/actions/release
        with:
          module: "oci"
